### ISSUE TITLE
19c Installer complains of low memory

### ISSUE THREAD

**Issue by yogiboy** [oracle/vagrant-projects#241]
Seems default memory for VM must be increased from current 2048M, to a higher value, in the Vagrantfile.

```shell
Warning:
oracle-19c-vagrant: [WARNING] [DBT-11209] Current available memory is less than the required available memory (1,536MB) for creating the database.
oracle-19c-vagrant:    CAUSE: Following nodes do not have required available memory :
oracle-19c-vagrant:  Node:oracle-19c-vagrant                Available memory:1.3859GB (1453176.0KB)
```

**Comment by PaulNeumann** [comment]
@yogiboy This warning occurs with both the 18.3.0 and 19.3.0 single-instance database boxes. It's fairly harmless; the boxes build and run fine as is. Increasing the VM memory to 3072 MB in the `Vagrantfile` eliminates the warning.

@gvenzl If you agree that this is a legitimate issue, and that increasing the VM memory to 3072 MB for the 18c and 19c boxes is the correct solution, I'd be happy to submit a PR.  (Or, if you'd prefer, I could add a commit to #230, since the affected files are already being updated there.)

**Comment by yogiboy** [comment]
> 
> 
> @yogiboy This warning occurs with both the 18.3.0 and 19.3.0 single-instance database boxes. It's fairly harmless; the boxes build and run fine as is. Increasing the VM memory to 3072 MB in the `Vagrantfile` eliminates the warning.
> 
> @gvenzl If you agree that this is a legitimate issue, and that increasing the VM memory to 3072 MB for the 18c and 19c boxes is the correct solution, I'd be happy to submit a PR. (Or, if you'd prefer, I could add a commit to #230, since the affected files are already being updated there.)

Nonethless, I recently came across this amazing repo. Thank you putting this together. I have just started learning vagrant etc.

**Comment by gvenzl** [comment]
Hi @PaulNeumann, I'm hesitant to increase the memory too much as still many laptops have only 8GB overall and it's unlikely that people will ever decrease the memory of the VM (why would they, things may break). It's handy to have multiple VMs running alongside, and users can always increase the memory if they wish to.

So, instead of increasing it to 3GB straight, why not just add the 200 (256) MBs that are required to get the installer not to raise that warning? And to round it up, just make it 2300MB, as 2304 looks just odd to me.

**Comment by PaulNeumann** [comment]
@gvenzl That makes sense. I'll test to make sure 2300 MB works for both 18c and 19c.  Do you want a separate PR for this, or do you want me to add it to #230? Right now, I think #230 is ready to go.

**Comment by gvenzl** [comment]
Hi @PaulNeumann, now that PR #230 is merged, mind if you provide a separate one for this one?

**Comment by PaulNeumann** [comment]
@gvenzl Will do.

**Comment by gsanjeevkumar** [comment]
I am running on Docker so what is the best way to expand/increase the memory using the docker run commands
thanks in advance.
