### ISSUE TITLE
No file syncing for Oracle Database VM

### ISSUE THREAD

**Issue by CuriousCactus** [oracle/vagrant-projects#298]
**Describe the issue**

vagrant up appeared to run fine, but when I ssh into the vm there are no synced files in the vagrant directory

**Environment (please complete the following information):**

- Host OS: Ubuntu 20
- Kernel version (for Linux host): 5.4.0-45-generic
- Vagrant version: 2.2.6
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 6.1.10_Ubuntur138449
  - For libvirt:
    - Vagrant-libvirt plugin version: 0.0.45
    - QEMU and libvirt version:  libvirt0:amd64 6.0.0-0ubuntu8.3, package qemu-kvm is not installed
- Vagrant project: OracleDatabase/19.3.0

**Comment by PaulNeumann** [comment]
@CuriousCactus It's not clear whether you're using the VirtualBox provider or the libvirt provider. (I'm _guessing_ libvirt, because Vagrant 2.2.6 has to be patched to support VirtualBox 6.1, but it's only a guess.)

Could you post the output of `vagrant up`? You can capture the output to a file called `vagrant.log` by running  
`vagrant up &> vagrant.log`. You won't see any output in your terminal while the command runs. If you still have the VM, the output should be fairly short. If you already destroyed the VM and need to start over, then please copy the output to a gist and reply with the link. That should help narrow down the issue.

**Comment by CuriousCactus** [comment]
I think I'm using virtualbox (oracle-19c-vagrant shows in the gui), so perhaps this is the issue.
`vagrant up` output is below.
I've shelved this for the moment, but perhaps the answer would help someone else.
Thanks!

```
Bringing machine 'oracle-19c-vagrant' up with 'virtualbox' provider...
==> oracle-19c-vagrant: Checking if box 'oraclelinux/7' version '7.8.128' is up to date...
==> oracle-19c-vagrant: Clearing any previously set forwarded ports...
==> oracle-19c-vagrant: Clearing any previously set network interfaces...
==> oracle-19c-vagrant: Preparing network interfaces based on configuration...
    oracle-19c-vagrant: Adapter 1: nat
==> oracle-19c-vagrant: Forwarding ports...
    oracle-19c-vagrant: 1521 (guest) => 1521 (host) (adapter 1)
    oracle-19c-vagrant: 5500 (guest) => 5500 (host) (adapter 1)
    oracle-19c-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> oracle-19c-vagrant: Running 'pre-boot' VM customizations...
==> oracle-19c-vagrant: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "d86be820-eb3f-4a73-8bc8-dc538c8d7a50", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'oracle-19c-vagrant' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

**Comment by AmedeeBulle** [comment]
This is a VirtualBox "issue" -- that is: VirtualBox can't start; the VirtualBox log file will probably tell you more, but typically it is because the kernel modules are not loaded.
Also bear in mind that you can't run another virtualization engine (e.g. KVM) and VirtualBox at the same time.

**Comment by PaulNeumann** [comment]
@CuriousCactus As @AmedeeBulle noted, VirtualBox and KVM can't run at the same time. Since you have libvirt installed on your host, it's possible that this is the problem (or at least _a_ problem). To make sure that the libvirt service is stopped and the VirtualBox service is started, run the following:

```bash
systemctl stop libvirtd.service
systemctl start vboxdrv.service
```

Then try `vagrant up` again to see whether it gets any farther.

**Comment by totalamateurhour** [comment]
Closing due to lack of follow up. @CuriousCactus - feel free to re-open should you have more diagnostics.
