### ISSUE TITLE
perform unzip quietly for oracle db software zip file

### ISSUE THREAD

**Issue by delassiops** [oracle/vagrant-projects#307]
AS  contribution guidelines... i open this issue To discuses pull request https://github.com/oracle/vagrant-projects/pull/306:

https://github.com/oracle/vagrant-projects/pull/306#issuecomment-699694666

https://github.com/oracle/vagrant-projects/pull/306#issuecomment-699694979

**Comment by delassiops** [comment]
I suggest to add a message (echo) at the start of operation then in the end: 

echo "INSTALLER: Extracting Oracle Database software. Please be patient..."
unzip -qq /vagrant/LINUX.X64_193000_db_home.zip -d $ORACLE_HOME/
echo "INSTALLER: Extracting Oracle Database software. Completed Successfully."

**Comment by PaulNeumann** [comment]
As noted in the comments on #306, there are drawbacks to unzipping the Oracle Database software silently. So, I agree with @Djelibeybi that if this is done, it should be optional and disabled by default. This would require modifying four files. For example:

### `.env`

Add a new configuration parameter, e.g., VM_USE_SILENT_UNZIP, probably right after the VM_ORACLE_EDITION parameter, since parameters are listed in roughly the order that they're used.

```plaintext
# Unzip Oracle Database software silently
# Faster, but VM provisioning may appear to hang
# VM_USE_SILENT_UNZIP=false
```

### `README.md`

Document the new configuration parameter, right after the VM_ORACLE_EDITION parameter.

```markdown
* `VM_USE_SILENT_UNZIP` (default: `false`): Unzip Oracle Database software silently. Faster, but VM provisioning may appear to hang.
```

### `Vagrantfile`

In the constant definition section, add code to evaluate the new configuration parameter, right after the VM_ORACLE_EDITION parameter.

```ruby
  # Unzip Oracle Database software silently
  # Faster, but VM provisioning may appear to hang
  VM_USE_SILENT_UNZIP = default_b('VM_USE_SILENT_UNZIP', false)
```

In the convenience methods section, add a new method, default_b, right after the default_i method.

```ruby
def default_b(key, default)
  default_s(key, default).to_s.downcase == "true"
end
```

Pass the value of the new configuration parameter to the `install.sh` script, right after the VM_ORACLE_EDITION parameter.

```ruby
       "USE_SILENT_UNZIP"    => VM_USE_SILENT_UNZIP,
```

### `install.sh`

Process the new configuration parameter. The actual unzip command doesn't need to change if the UNZIP environment variable is used.

```bash
if [[ "${USE_SILENT_UNZIP,,}" == 'true' ]]; then
  UNZIP=-qq
  export UNZIP
  echo 'INSTALLER: Extracting Oracle Database software. Please be patient...'
fi
unzip /vagrant/LINUX.X64_193000_db_home.zip -d $ORACLE_HOME/
unset UNZIP
```

To keep the single-instance database projects consistent, these changes would need to be made for the 12.1.0.2, 12.2.0.1, 18.3.0, and 19.3.0 projects.

This is only one possible approach. The decision on whether and how to implement the proposed enhancement is entirely up to the code owner.

**Comment by totalamateurhour** [comment]
Thank you for your detailed example, @PaulNeumann, and thank you for your suggestion @delassiops. At the moment, this is not a feature we feel is worth including in this Vagrant project.
