### ISSUE TITLE
Automatic detection of host env variables

### ISSUE THREAD

**Issue by gvenzl** [oracle/vagrant-projects#35]
The idea is that the Vagrantfile script automatically detects certain environment variables from the host and passes those one, therefore not requiring the user to manually change the Vagrantfile any longer for customizations. The idea would be:

```
export ORACLE_HOME=/home/oracle/database
export ORACLE_SID=MYDB
vagrant up
```

Vagrant then automatically detects those and sets them for the VM as well, rather than having the user to go into the Vagrantfile itself and set those.

**Comment by scoter-oracle** [comment]
We can evaluate to introduce "vagrant-env" plugin:

https://github.com/gosuri/vagrant-env

**Comment by PaulNeumann** [comment]
The vagrant-env plugin might be a good option for this, assuming that it works as advertised. It wouldn't really use the host's environment variables, but it would put all of the configuration options in one file, which should reduce the need to edit the Vagrantfile. It has a couple of other advantages, too:

* The syntax is consistent across host OSs (wouldn't have to explain `export ORACLE_HOME=...` on Linux vs. `set ORACLE_HOME=...` on Windows).

* With the plugin, users wouldn't need to modify host environment variables that should be different between host and guest before running `vagrant up`. For example, if the user has an Oracle client on the host, they probably wouldn't want to use the same ORACLE_HOME path for the guest. If the host is Windows, it wouldn't work anyway, because the host's path would look like C:\path\to\oracle.

If you'd like to investigate the plugin, I'd be happy to work on it.

**Comment by AmedeeBulle** [comment]
Note that your 2nd use case is not fully valid: environment takes precedence on `.env` file.  
(See [Why is it not overriding existing ENV variables?](https://github.com/bkeepers/dotenv#why-is-it-not-overriding-existing-env-variables))

My own view on this:
- I don't like using environment variables to configure Vagrantfiles because they are not persistent and after the facts you cannot trace how a box has been configured during provisioning.
- `.env` file solves this nicely -- this is the approach taken by `docker-compose` -- but we need to be careful in choosing variable names to avoid potential clash with the user environment. In the above situation I would use something like `VAGRANT_ORACLE_HOME` as variable in file rather than just `ORACLE_HOME`
- I don't fully agree with the plugin author on [Should I commit my .env file?](https://github.com/gosuri/vagrant-env#should-i-commit-my-env-file). It is a pain for the developers: changing `.env` will mark the git tree dirty and eventually somebody will commit by accident its own `.env` which may contain sensitive information. I usually have `.env` in .gitignore and add e.g. a `.env.example` which can be used as template.

**Comment by PaulNeumann** [comment]
Thanks! I appreciate your insight.

I didn't realize that vagrant-env wouldn't override existing environment variables. That's obviously important, and it doesn't seem to be documented for the plugin itself. Using variable names like `VAGRANT_ORACLE_HOME` to avoid conflicts with the host environment makes sense.

I agree with your view on committing `.env`. Adding `.env` to `.gitignore` and providing `.env.example` (or perhaps `.env.default`?) seems like a good approach. Having the user copy `.env.example` to `.env` before running `vagrant up` the first time would add a step to the process, though. I think it would be helpful to have the Vagrantfile copy `.env.example` to `.env`, if `.env` doesn't already exist.

**Comment by AmedeeBulle** [comment]
FWIW, here is my take on this: #56 

This is my personal view and might not be applicable as such in all cases.  
My objectives/requirements were:
- Plugin should not be mandatory. Defaults should be the same and user has choice to use `.env` files or edit the Vagrantfile.
- I wanted to easily handle strings/integer/boolean variables (all environment variables are strings, compared to constants in the Vagrantfile you loose the type)
- An empty variable in `.env` files or environment should not override default value in the Vagrantfile

For the `.env` files I eventually decided to commit  `.env` with default values in the source tree and allow user to override in `.env.local` (which is in `.gitignore`) -- based on [What other .env* files can I use?](https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use).

> I didn't realize that vagrant-env wouldn't override existing environment variables.

Actually you could do it by using `overload` instead of `load`, but I don't think it is a good idea as it is not the common practice.

**Comment by PaulNeumann** [comment]
If you'd still like to implement this enhancement for the database boxes, I'd be happy to work on it. I understand @AmedeeBulle's approach, and I could handle it the same way.

**Comment by gvenzl** [comment]
Hey everyone, is this still an unresolved ER or has something changed in the meantime?

**Comment by PaulNeumann** [comment]
I think there's value in this ER. Setting environment variables or (optionally) using the vagrant-env plugin would be much more convenient than modifying the `Vagrantfile`s. It would also reduce the risk of accidentally committing a modified `Vagrantfile`. With your approval, I'd be happy to work on this for the single-instance database boxes.

**Comment by Djelibeybi** [comment]
We use the `vagrant-env` plugin with the OLCNE stuff, so I think standardising on having sane defaults and allowing overrides via `.env.local` is sensible.

**Comment by PaulNeumann** [comment]
I'd already done some of the work for this enhancement locally, so I've submitted a WIP PR for discussion.

**Comment by AmedeeBulle** [comment]
@gvenzl I believe we can close this one as it has been implemented in projects where it makes sense

**Comment by totalamateurhour** [comment]
Closing per @AmedeeBulle
