### ISSUE TITLE
VDI  file format instead of VMDK

### ISSUE THREAD

**Issue by rikumabokss** [oracle/vagrant-projects#410]
Hi,

Is there any way to change from VMDK to VDI in VMs of OCNE.

Thanks

**Comment by AmedeeBulle** [comment]
Each VM is a Vagrant box of its own and the Vagrant boxes (images) are in VMDK format.

There is currently no way to _import_ the images as VDI with Vagrant -- see [VirtualBox: Support VDI with package command](https://github.com/hashicorp/vagrant/issues/10677)

**Comment by mselseth** [comment]
Created Ubuntu VM base with Virtual Box, planning to use it in vagrant. Reading this issue, does it mean that I should create the VM in vmdk format to package it for vagrant?
using VB 6.1.32, vagrant 2.2.19. Not clear if this issue is present with these versions.

The original issue I am having, I see files inside VM showing as zero size after VM reboots, inside VM, non repeatable, so I decided to create VM base myself under VB just to root cause it.

Looks like a corruption of the fs somehow...

Where can I locate documentation that shows vagrant needs VMDK disk format, and that VDI format should not be used.
Also, is VMDK going to work using dynamically allocated?

Thank you.

**Comment by AmedeeBulle** [comment]
The Vagrant issue posted in my previous answer clearly states that VDI is not supported yet by Vagrant.

This repo is for Vagrant projects using Oracle Linux boxes, for generic Vagrant questions, you should reach out to the Vagrant community.
