### ISSUE TITLE
OracleLinux/9 project?

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-projects#451]
If you'd like to add an OracleLinux/9 project (and you're not already working on one), I have one ready. It's essentially a copy of the OracleLinux/8 project with the version number changed.

**Comment by AmedeeBulle** [comment]
Hi Paul!

This is on my ToDO list since quite some time, but never got a the chance to do it.
So PR is welcome!

For the people who want to "extend"  that project you might want to add a note in comments in the Vagrantfile re. the use of virtio nic type when additional network interfaces are used (see #442)

Thanks
